/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.28.0-171-g701045206 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.28.0-171-g701045206"
#endif
#define SDL_REVISION_NUMBER 0
